UPDATE ModifierStrings SET Text = 'BR_LOC_PREVIEW_BARDING' WHERE ModifierId = 'TOP_COVER_DEFENSE_BONUS_VS_RANGED' AND Context = 'Preview' ;
UPDATE ModifierStrings SET Text = 'BR_LOC_PREVIEW_INTERCEPTOR' WHERE ModifierId = 'INTERCEPTOR_BONUS_VS_BOMBERS' AND Context = 'Preview' ;
UPDATE ModifierStrings SET Text = 'BR_LOC_PREVIEW_DRONE_STRENGTH' WHERE ModifierId = 'BOMBARD_STR_BUFF_FROM_DRONE' AND Context = 'Preview' ;
INSERT INTO ModifierStrings (ModifierId, Context, Text) VALUES ('DEFENDER_ADJUST_CITY_DEFENSE_STRENGTH', 'Preview', 'BR_LOC_PREVIEW_REDOUBT') ;