-- ('', '', 'en_US'),

INSERT OR REPLACE INTO LocalizedText 
(Tag, Text, Language) VALUES
('LOC_BR_LABEL', ' [COLOR:SuzerainDark][BR][ENDCOLOR]', 'en_US'),
('LOC_BR_HEADER', '[ICON_Reports][COLOR:SuzerainDark]BETTER RULEBOOK[ENDCOLOR][ICON_Reports][NEWLINE][NEWLINE]', 'en_US'),
('LOC_OT_HEADER', '[NEWLINE][NEWLINE][COLOR_Red]ORIGINAL TEXT[ENDCOLOR][NEWLINE][NEWLINE]', 'en_US'),

/***** Combat Previews  *****/
('LOC_COMBAT_PREVIEW_ESPIONAGE_BONUS', '+{1_Value} Higher Diplomatic Visibility{LOC_BR_LABEL}', 'en_US'),
('LOC_COMBAT_PREVIEW_FORTIFIED_DEFENSE_DESC', '+{1_Value} Fortified Unit{LOC_BR_LABEL}', 'en_US'),


/***** CITY/ENCAMPMENT BANNERS AND FLOATERS *****/
('LOC_CITY_BANNER_GARRISON_DEFENSE_STRENGTH', 'Defense Strength{LOC_BR_LABEL}', 'en_US'),
('LOC_CITY_BANNER_OUTER_DEFENSE_HITPOINTS', 'Wall health{LOC_BR_LABEL}: {1_Health}', 'en_US'),
('LOC_HUD_UNIT_PANEL_WALL_HEALTH_TOOLTIP', 'Wall health{LOC_BR_LABEL}: {1_CurrentHealth}/{2_MaxHealth}', 'en_US'),
('LOC_CITY_BANNER_GARRISON_HITPOINTS', 'City health{LOC_BR_LABEL}: {1_Health}', 'en_US'),
('LOC_CITY_BANNER_DISTRICT_HITPOINTS', 'Encampment health{LOC_BR_LABEL}: {1_Health}', 'en_US'),
('LOC_WORLD_DISTRICT_DEFENSE_DAMAGE_DECREASE_FLOATER', '[COLOR_GREEN]+{1_Num}[ENDCOLOR] Walls', 'en_US'),
('LOC_WORLD_DISTRICT_DEFENSE_DAMAGE_INCREASE_FLOATER', '[COLOR_RED]{1_Num}[ENDCOLOR] Walls', 'en_US'),
('LOC_WORLD_DISTRICT_GARRISON_DAMAGE_DECREASE_FLOATER', '[COLOR_GREEN]+{1_Num}[ENDCOLOR] Health', 'en_US'),
('LOC_WORLD_DISTRICT_GARRISON_DAMAGE_INCREASE_FLOATER', '[COLOR_RED]{1_Num}[ENDCOLOR] Health', 'en_US')

;


